version: '3.8'

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - "3000:3000"
      - "53:53/udp"
      - "80:80"
    volumes:
      - adguard_config:/opt/adguardhome/conf
      - adguard_work:/opt/adguardhome/work
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - tailscale_var:/var/lib/tailscale
    restart: unless-stopped
    command: tailscaled

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup --interval 3600

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  fail2ban:
    image: crazymax/fail2ban
    container_name: fail2ban
    network_mode: host
    volumes:
      - /var/log:/var/log:ro
      - ./fail2ban:/data
    restart: unless-stopped

  portnote:
    image: crocofied/portnote:latest
    container_name: portnote
    ports:
      - "3001:3000"
    restart: unless-stopped

volumes:
  adguard_config:
  adguard_work:
  tailscale_var:
