name: CI/CD Pipeline for home server
description: This workflow deploys the latest changes to the home server when code is pushed to the main branch.

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: push to Remote Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
